# Generated by Django 4.2.15 on 2024-08-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code_bar',
            new_name='barcode',
        ),
    ]
